---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: web
    tier: db
spec:
  containers:
    - name: mongodb
      imagePullPolicy: Always
      image: pavanikakarlapudi/mongodb:v1
      ports:
        - containerPort: 27017
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    name: mongodb
    tier: db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 27017

